### ISSUE TITLE
Doesn't work with core-js v3

### ISSUE THREAD

**Issue by vsolanogo** [cometkim/gatsby-plugin-linaria#50]
Works fine with v2, will this package be updated in the future to support v3?

detailed error: 
success run queries - 6.543s - 236/236 36.07/s

ERROR #98123  WEBPACK

Generating SSR bundle failed

Cannot find module 'core-js/modules/es6.regexp.to-string'

File: .cache\develop-static-entry.js

**Comment by silvenon** [comment]
Unfortunately this seems to be a problem upstream. 😕 callstack/linaria#420

**Comment by cometkim** [comment]
And also gatsby, they still use core-js v2 and planned to drop it in gatsby 3. (yeah it's long term plan)

**Comment by gustavpursche** [comment]
Hi there,
I'm facing a similar problem:

```
Error: Cannot find module 'core-js/modules/es.array.for-each'
Require stack:
- /home/gustav/Development/stav.dev/node_modules/gatsby/dist/utils/webpack.config.js
- /home/gustav/Development/stav.dev/node_modules/gatsby/dist/commands/develop.js
- /home/gustav/Development/stav.dev/node_modules/gatsby/node_modules/gatsby-cli/lib/create-cli.js
- /home/gustav/Development/stav.dev/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js
- /home/gustav/Development/stav.dev/node_modules/gatsby/dist/bin/gatsby.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.resolve (internal/modules/cjs/helpers.js:80:19)
    at isExternal (/home/gustav/Development/stav.dev/node_modules/gatsby/dist/utils/webpack.config.js:507:31)
    at config.externals (/home/gustav/Development/stav.dev/node_modules/gatsby/dist/utils/webpack.config.js:518:24)
    at handleExternals (/home/gustav/Development/stav.dev/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:78:17)
    at next (/home/gustav/Development/stav.dev/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:66:9)
    at handleExternals (/home/gustav/Development/stav.dev/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:71:7)
    at /home/gustav/Development/stav.dev/node_modules/webpack/lib/ExternalModuleFactoryPlugin.js:101:5
    at /home/gustav/Development/stav.dev/node_modules/webpack/lib/NormalModuleFactory.js:400:5
    at AsyncSeriesWaterfallHook.eval [as callAsync] (eval at create (/home/gustav/Development/stav.dev/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
    at NormalModuleFactory.create (/home/gustav/Development/stav.dev/node_modules/webpack/lib/NormalModuleFactory.js:381:28)
    at /home/gustav/Development/stav.dev/node_modules/webpack/lib/Compilation.js:897:14
    at Semaphore.acquire (/home/gustav/Development/stav.dev/node_modules/webpack/lib/util/Semaphore.js:29:4)
    at asyncLib.forEach.err.stack (/home/gustav/Development/stav.dev/node_modules/webpack/lib/Compilation.js:895:15)
    at arrayEach (/home/gustav/Development/stav.dev/node_modules/neo-async/async.js:2405:9)
    at Object.each (/home/gustav/Development/stav.dev/node_modules/neo-async/async.js:2846:9) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/gustav/Development/stav.dev/node_modules/gatsby/dist/utils/webpack.config.js',
    '/home/gustav/Development/stav.dev/node_modules/gatsby/dist/commands/develop.js',
    '/home/gustav/Development/stav.dev/node_modules/gatsby/node_modules/gatsby-cli/lib/create-cli.js',
    '/home/gustav/Development/stav.dev/node_modules/gatsby/node_modules/gatsby-cli/lib/index.js',
    '/home/gustav/Development/stav.dev/node_modules/gatsby/dist/bin/gatsby.js'
  ]
}
```

Do you already have plan how to resolve this? Do you need any help with it?

**Comment by gustavpursche** [comment]
Hi, I just wanted to ask what the status of this issue is? As far as I can see core-js v3 support was added in the recent beta and it seems, that this issue should be resolved according to https://github.com/callstack/linaria/issues/539.

I tried installing `linaria@1.4.0-beta.3` but got the same error.

**Comment by silvenon** [comment]
Apart from incorrectly built stable versions of Linaria the problem was also the discrepancy in versions of core-js between Linaria and Gatsby, so the full workaround is to also install core-js v3 locally:

```sh
yarn add linaria@^1.4.0-beta.3
yarn add core-js
```

I also documented this in the readme under FAQ.

**Comment by BlackFenix2** [comment]
@silvenon yep, thats pretty much what i had to do for my local project.

**Comment by cometkim** [comment]
This will be fixed in linaria@next (v2.0) they will not depend on core-js anymore

**Comment by cometkim** [comment]
And Gatsby finally switched their core-js dependency to version 3

https://github.com/gatsbyjs/gatsby/issues/15601

**Comment by cometkim** [comment]
Linaria v2 has been released without core-js dependency. closing issue.
